//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecuenciasGeneros
    {
        public int Id { get; set; }
        public Nullable<int> SecuenciaDR { get; set; }
        public Nullable<int> SecuenciaCF { get; set; }
        public Nullable<int> SecuenciaRO { get; set; }
        public Nullable<int> SecuenciaDI { get; set; }
        public Nullable<int> SecuenciaIN { get; set; }
        public Nullable<int> SecuenciaSU { get; set; }
    }
}
